permalink: /:year/:month/:day/:title/
pygments: true
markdown: kramdown
tag_dir: tags
tag_title_prefix:
paginate: 5

baseurl: /
live_url: http://blog.antkim.com

title : This is my homepage
name : Anthony


assets:
  js_compressor: uglifier
  css_compressor: sass
version: 1