permalink: /:year/:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "Rakefile", "TODO.md", "sass_converter.rb", "Gemfile", "Gemfile.lock", ".tm_properties", "config.rb", "sass", "CNAME", "Procfile"]

baseurl: /
live_url: http://www.projectantman.com

title : This is my homepage
tagline: project antman
author :
  name : Anthony